/* Generated by txiCfg */
/* Data define file. */


#define TMAX_TSK_OBJ       17
#define TMAX_SEM_OBJ        2
#define TMAX_FLG_OBJ        8
#define TMAX_DTQ_OBJ        3
#define TMAX_MBX_OBJ       17
#define TMAX_MPF_OBJ        2
#define TMAX_CYC_OBJ        3

#define ID_MAIN_TASK        1
#define ID_MUSB_TASK        2
#define ID_LINE_TASK        3
#define ID_FEED_TASK        4
#define ID_STACKER_TASK     5
#define ID_DISCRIMINATION_TASK    6
#define ID_SENSOR_TASK      7
#define ID_TIMER_TASK       8
#define ID_DISPLAY_TASK     9
#define ID_CENTERING_TASK   10
#define ID_APB_TASK        11
#define ID_MOTOR_TASK      12
#define ID_IDLE_TASK       13
#define ID_ERRDISP_TASK    14
#define ID_SUBCPU_TASK     15
#define ID_ICB_TASK        16
#define ID_DLINE_TASK      17
#define ID_SENSOR_FLAG      1
#define ID_FEED_CTRL_FLAG    2
#define ID_STACKER_CTRL_FLAG    3
#define ID_CENTERING_CTRL_FLAG    4
#define ID_APB_CTRL_FLAG    5
#define ID_UART_TX_FLAG     6
#define ID_SUBCPU_CTRL_FLAG    7
#define ID_ICB_CTRL_FLAG    8
#define ID_SEM1             1
#define ID_TRACE_SEM        2
#define ID_UART_RX_DTQ      1
#define ID_UART_RX_SUBCPU_DTQ    2
#define ID_UART_ICB_RX_DTQ    3
#define ID_MAIN_MBX         1
#define ID_MUSB_MBX         2
#define ID_LINE_MBX         3
#define ID_FEED_MBX         4
#define ID_STACKER_MBX      5
#define ID_DISCRIMINATION_MBX    6
#define ID_SENSOR_MBX       7
#define ID_TIMER_MBX        8
#define ID_DISPLAY_MBX      9
#define ID_CENTERING_MBX   10
#define ID_APB_MBX         11
#define ID_MOTOR_MBX       12
#define ID_IDLE_MBX        13
#define ID_ERRDISP_MBX     14
#define ID_SUBCPU_MBX      15
#define ID_ICB_MBX         16
#define ID_DLINE_MBX       17
#define ID_MBX_MPF          1
#define ID_MBX_MAIN_MPF     2
#define ID_TIMER_1MS_CYC    1
#define ID_TIMER_10MS_CYC    2
#define ID_TIMER_100MS_CYC    3

