/* Generated by txiCfg */

#define _KERNEL_CFG_DATADEFINE_
#include "kernel_id.h"
#include "txi_data.h"

/* Kernel configration data */
_KERNEL_UITRON_TSK _kernel_tsk[TMAX_TSK_OBJ];
VP _kernel_tsk_id[TMAX_TSK_OBJ];
INT _kernel_tsk_maxid = TMAX_TSK_OBJ;

_KERNEL_UITRON_SEM _kernel_sem[TMAX_SEM_OBJ];
VP _kernel_sem_id[TMAX_SEM_OBJ];
INT _kernel_sem_maxid = TMAX_SEM_OBJ;

_KERNEL_UITRON_FLG _kernel_flg[TMAX_FLG_OBJ];
VP _kernel_flg_id[TMAX_FLG_OBJ];
INT _kernel_flg_maxid = TMAX_FLG_OBJ;

_KERNEL_UITRON_DTQ _kernel_dtq[TMAX_DTQ_OBJ];
VP _kernel_dtq_id[TMAX_DTQ_OBJ];
INT _kernel_dtq_maxid = TMAX_DTQ_OBJ;

_KERNEL_UITRON_MBX _kernel_mbx[TMAX_MBX_OBJ];
VP _kernel_mbx_id[TMAX_MBX_OBJ];
int _kernel_mbx_maxid = TMAX_MBX_OBJ;

_KERNEL_UITRON_MPF _kernel_mpf[TMAX_MPF_OBJ];
VP _kernel_mpf_id[TMAX_MPF_OBJ];
INT _kernel_mpf_maxid = TMAX_MPF_OBJ;

_KERNEL_UITRON_CYC _kernel_cyc[TMAX_CYC_OBJ];
VP _kernel_cyc_id[TMAX_CYC_OBJ];
INT _kernel_cyc_maxid = TMAX_CYC_OBJ;

#include "demo_itron.h"

#include "msg_port.h"

#include "sio.h"

#define STACK_SIZE 1024

char _tsk_stack_ID_MAIN_TASK[STACK_SIZE];
char _tsk_stack_ID_MUSB_TASK[STACK_SIZE];
char _tsk_stack_ID_LINE_TASK[STACK_SIZE];
char _tsk_stack_ID_FEED_TASK[STACK_SIZE];
char _tsk_stack_ID_STACKER_TASK[STACK_SIZE];
char _tsk_stack_ID_DISCRIMINATION_TASK[STACK_SIZE];
char _tsk_stack_ID_SENSOR_TASK[STACK_SIZE];
char _tsk_stack_ID_TIMER_TASK[STACK_SIZE];
char _tsk_stack_ID_DISPLAY_TASK[STACK_SIZE];
char _tsk_stack_ID_CENTERING_TASK[STACK_SIZE];
char _tsk_stack_ID_APB_TASK[STACK_SIZE];
char _tsk_stack_ID_MOTOR_TASK[STACK_SIZE];
char _tsk_stack_ID_IDLE_TASK[STACK_SIZE];
char _tsk_stack_ID_ERRDISP_TASK[STACK_SIZE];
char _tsk_stack_ID_SUBCPU_TASK[STACK_SIZE];
char _tsk_stack_ID_ICB_TASK[STACK_SIZE];
char _tsk_stack_ID_DLINE_TASK[STACK_SIZE];
VP_INT _dtq_data_ID_UART_RX_DTQ[10];
VP_INT _dtq_data_ID_UART_RX_SUBCPU_DTQ[10];
VP_INT _dtq_data_ID_UART_ICB_RX_DTQ[10];
char _mpf_data_ID_MBX_MPF[TSZ_MPF(16, MSG_PACKET)];
char _mpf_data_ID_MBX_MAIN_MPF[TSZ_MPF(16, MSG_PACKET)];

#ifndef DISABLE_CFG_MAIN
/* Define main entry point. */
int main()
{
    /* Enter the ThreadX kernel. */
    tx_kernel_enter();

    return 0;
}
#endif

/* Define what the initial system looks like. */
void tx_application_define(void *first_unused_memory)
{
    ER ercd;
    T_CTSK ctsk;
    T_CSEM csem;
    T_CFLG cflg;
    T_CDTQ cdtq;
    T_CMBX cmbx;
    T_CMPF cmpf;
    T_CCYC ccyc;

    txi_init(first_unused_memory);

    ctsk.tskatr = TA_HLNG|TA_ACT;
    ctsk.exinf = (VP_INT)ID_MAIN_TASK;
    ctsk.task = (FP)main_task;
    ctsk.itskpri = 15;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_MAIN_TASK;
    ercd = cre_tsk(ID_MAIN_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_MUSB_TASK;
    ctsk.task = (FP)musb_task;
    ctsk.itskpri = 8;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_MUSB_TASK;
    ercd = cre_tsk(ID_MUSB_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_LINE_TASK;
    ctsk.task = (FP)line_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_LINE_TASK;
    ercd = cre_tsk(ID_LINE_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_FEED_TASK;
    ctsk.task = (FP)feed_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_FEED_TASK;
    ercd = cre_tsk(ID_FEED_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_STACKER_TASK;
    ctsk.task = (FP)stacker_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_STACKER_TASK;
    ercd = cre_tsk(ID_STACKER_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_DISCRIMINATION_TASK;
    ctsk.task = (FP)discrimination_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_DISCRIMINATION_TASK;
    ercd = cre_tsk(ID_DISCRIMINATION_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_SENSOR_TASK;
    ctsk.task = (FP)sensor_task;
    ctsk.itskpri = 5;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_SENSOR_TASK;
    ercd = cre_tsk(ID_SENSOR_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_TIMER_TASK;
    ctsk.task = (FP)timer_task;
    ctsk.itskpri = 5;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_TIMER_TASK;
    ercd = cre_tsk(ID_TIMER_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_DISPLAY_TASK;
    ctsk.task = (FP)display_task;
    ctsk.itskpri = 5;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_DISPLAY_TASK;
    ercd = cre_tsk(ID_DISPLAY_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_CENTERING_TASK;
    ctsk.task = (FP)centering_task;
    ctsk.itskpri = 8;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_CENTERING_TASK;
    ercd = cre_tsk(ID_CENTERING_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_APB_TASK;
    ctsk.task = (FP)apb_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_APB_TASK;
    ercd = cre_tsk(ID_APB_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_MOTOR_TASK;
    ctsk.task = (FP)motor_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_MOTOR_TASK;
    ercd = cre_tsk(ID_MOTOR_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_IDLE_TASK;
    ctsk.task = (FP)idle_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_IDLE_TASK;
    ercd = cre_tsk(ID_IDLE_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_ERRDISP_TASK;
    ctsk.task = (FP)errdisp_task;
    ctsk.itskpri = 16;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_ERRDISP_TASK;
    ercd = cre_tsk(ID_ERRDISP_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_SUBCPU_TASK;
    ctsk.task = (FP)subcpu_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_SUBCPU_TASK;
    ercd = cre_tsk(ID_SUBCPU_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_ICB_TASK;
    ctsk.task = (FP)icb_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_ICB_TASK;
    ercd = cre_tsk(ID_ICB_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    ctsk.tskatr = TA_HLNG;
    ctsk.exinf = (VP_INT)ID_DLINE_TASK;
    ctsk.task = (FP)dline_task;
    ctsk.itskpri = 3;
    ctsk.stksz = STACK_SIZE;
    ctsk.stk = _tsk_stack_ID_DLINE_TASK;
    ercd = cre_tsk(ID_DLINE_TASK, &ctsk);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_SENSOR_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_FEED_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_STACKER_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_CENTERING_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_APB_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_UART_TX_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_SUBCPU_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    cflg.flgatr = TA_TFIFO|TA_CLR|TA_WSGL;
    cflg.iflgptn = 0;
    ercd = cre_flg(ID_ICB_CTRL_FLAG, &cflg);
    if(ercd!=E_OK) while(1);

    csem.sematr = TA_TFIFO;
    csem.isemcnt = 0;
    csem.maxsem = 10;
    ercd = cre_sem(ID_SEM1, &csem);
    if(ercd!=E_OK) while(1);

    csem.sematr = TA_TFIFO;
    csem.isemcnt = 0;
    csem.maxsem = 10;
    ercd = cre_sem(ID_TRACE_SEM, &csem);
    if(ercd!=E_OK) while(1);

    cdtq.dtqatr = TA_TFIFO;
    cdtq.dtqcnt = 10;
    cdtq.dtq = _dtq_data_ID_UART_RX_DTQ;
    ercd = cre_dtq(ID_UART_RX_DTQ, &cdtq);
    if(ercd!=E_OK) while(1);

    cdtq.dtqatr = TA_TFIFO;
    cdtq.dtqcnt = 10;
    cdtq.dtq = _dtq_data_ID_UART_RX_SUBCPU_DTQ;
    ercd = cre_dtq(ID_UART_RX_SUBCPU_DTQ, &cdtq);
    if(ercd!=E_OK) while(1);

    cdtq.dtqatr = TA_TFIFO;
    cdtq.dtqcnt = 10;
    cdtq.dtq = _dtq_data_ID_UART_ICB_RX_DTQ;
    ercd = cre_dtq(ID_UART_ICB_RX_DTQ, &cdtq);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_MAIN_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_MUSB_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_LINE_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_FEED_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_STACKER_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_DISCRIMINATION_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_SENSOR_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_TIMER_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_DISPLAY_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_CENTERING_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_APB_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_MOTOR_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_IDLE_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_ERRDISP_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_SUBCPU_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_ICB_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmbx.mbxatr = TA_TFIFO|TA_MFIFO;
    cmbx.maxmpri = 10;
    cmbx.mprihd = NULL;
    ercd = cre_mbx(ID_DLINE_MBX, &cmbx);
    if(ercd!=E_OK) while(1);

    cmpf.mpfatr = TA_TFIFO;
    cmpf.blkcnt = 16;
    cmpf.blksz = MSG_PACKET;
    cmpf.mpf = _mpf_data_ID_MBX_MPF;
    ercd = cre_mpf(ID_MBX_MPF, &cmpf);
    if(ercd!=E_OK) while(1);

    cmpf.mpfatr = TA_TFIFO;
    cmpf.blkcnt = 16;
    cmpf.blksz = MSG_PACKET;
    cmpf.mpf = _mpf_data_ID_MBX_MAIN_MPF;
    ercd = cre_mpf(ID_MBX_MAIN_MPF, &cmpf);
    if(ercd!=E_OK) while(1);

    ccyc.cycatr = TA_HLNG;
    ccyc.exinf = (VP_INT)NULL;
    ccyc.cychdr = (FP)timer_1ms_cyc;
    ccyc.cyctim = 1;
    ccyc.cycphs = 1;
    ercd = cre_cyc(ID_TIMER_1MS_CYC, &ccyc);
    if(ercd!=E_OK) while(1);

    ccyc.cycatr = TA_HLNG;
    ccyc.exinf = (VP_INT)NULL;
    ccyc.cychdr = (FP)timer_10ms_cyc;
    ccyc.cyctim = 10;
    ccyc.cycphs = 1;
    ercd = cre_cyc(ID_TIMER_10MS_CYC, &ccyc);
    if(ercd!=E_OK) while(1);

    ccyc.cycatr = TA_HLNG;
    ccyc.exinf = (VP_INT)NULL;
    ccyc.cychdr = (FP)timer_100ms_cyc;
    ccyc.cyctim = 100;
    ccyc.cycphs = 1;
    ercd = cre_cyc(ID_TIMER_100MS_CYC, &ccyc);
    if(ercd!=E_OK) while(1);
}

