TARGET_NAME:=boot
BUILD_DIR:=_build
MAKE_COMMON:=../Common


ROOT_PROJ:=./


CCFLAGS=\


CXFLAGS=\


ASMFLAG=\


LDFLAGS=\


SRC_FILES=\
	$(ROOT_PROJ)/main.c\


INC_FOLDER=\


LIBS=\



.PHONY:	default help

default: $(TARGET_NAME)


include $(MAKE_COMMON)/Makefile.common


$(foreach target, $(TARGET_NAME), $(call define_target, $(target)))



help:
	@echo  help



flash:


erase:

