TARGETS:=bootloader
PROJ_DIR:=
BUILD_DIR:=_build
MAKECOMMON_DIR:=../Common



CFLAGS:=

ASMFLAGS:=

LDFLAS:=


LIBS:=


SRC_FILES:=\


INC_FOLDER:=\


.PHONY:	default help

default: $(TARGETS)

include $(MAKECOMMON_DIR)/Makefile.common


$(foreach target, $(TARGETS), $(call define_targets, $(target)))


help:
	echo help


flash:


earase:



